# Shared helper for ADM Scheduled Task installers.
#
# "-WindowStyle Hidden" on a directly-registered "powershell.exe" Scheduled
# Task action only hides the console *after* Windows has already created (and
# briefly shown) it, and does nothing for grandchild processes. This routes
# the exact same PowerShell invocation through a generated hidden VBS wrapper
# instead: WshShell.Run(cmd, 0, True) sets the window style to hidden before
# the process is even created, which is what actually eliminates the flash.
# The legacy PowerShell arguments themselves are untouched -- only the
# top-level launch mechanism changes.

function New-AdmHiddenScheduledTaskAction {
    param(
        [Parameter(Mandatory = $true)][string]$RepositoryPath,
        [Parameter(Mandatory = $true)][string]$WrapperName,
        [Parameter(Mandatory = $true)][string]$PowerShellArguments
    )

    $escapedArgs = $PowerShellArguments.Replace('"', '""')
    $vbsDir = Join-Path $RepositoryPath "manager\generated"
    New-Item -ItemType Directory -Force -Path $vbsDir | Out-Null
    $vbsPath = Join-Path $vbsDir "$WrapperName.vbs"

    $vbsLines = @(
        "' Auto-generated by AdmHiddenLaunch.ps1 -- regenerated on every install, do not edit by hand.",
        "' Runs PowerShell with a truly hidden window (WshShell.Run windowStyle=0) so Task",
        "' Scheduler never flashes a console, and propagates the real exit code so",
        "' LastTaskResult stays meaningful.",
        "Set shell = CreateObject(""WScript.Shell"")",
        "exitCode = shell.Run ""powershell.exe $escapedArgs"", 0, True",
        "WScript.Quit exitCode"
    )
    Set-Content -LiteralPath $vbsPath -Value $vbsLines -Encoding ASCII

    return New-ScheduledTaskAction -Execute "wscript.exe" -Argument "`"$vbsPath`""
}
