# Shared helper for ADM Scheduled Task installers.
#
# "-WindowStyle Hidden" on a directly-registered "powershell.exe" Scheduled
# Task action only hides the console *after* Windows has already created (and
# briefly shown) it, and does nothing for grandchild processes. This routes
# the exact same PowerShell invocation through a generated hidden VBS wrapper
# instead: WshShell.Run(cmd, 0, True) sets the window style to hidden before
# the process is even created, which is what actually eliminates the flash.
# The legacy PowerShell arguments themselves are untouched -- only the
# top-level launch mechanism changes.

function New-AdmHiddenScheduledTaskAction {
    param(
        [Parameter(Mandatory = $true)][string]$RepositoryPath,
        [Parameter(Mandatory = $true)][string]$WrapperName,
        [Parameter(Mandatory = $true)][string]$PowerShellArguments,
        # Overrides where the generated .vbs wrapper is written. Defaults to
        # the production location under $RepositoryPath so real installs
        # (install_command_watcher.ps1, install_drive_dispatch_ingress.ps1
        # called without this param) are byte-for-byte unchanged. Callers
        # under test pass an isolated temp directory here so a Pester run
        # invoked against a real checkout can never overwrite that
        # checkout's live production wrapper file on disk -- see
        # fix/pester-scheduled-task-isolation-20260823.
        [string]$GeneratedWrapperDir
    )

    # System-level fail-closed guard: every hidden Scheduled Task installer
    # (install_command_watcher.ps1, install_drive_dispatch_ingress.ps1, and
    # any future one) routes its wrapper write through this one function,
    # so this is the one place that can protect all of them regardless of
    # whether a given installer script itself remembers to isolate its own
    # test invocations. When $env:ADM_PESTER_TEST_ACTIVE is set (a Pester
    # run sets it for the duration of its own It blocks -- see
    # DriveDispatchIngress.Tests.ps1), refuse -- before any New-Item or
    # Set-Content below -- to write into the real repository tree's
    # manager\generated\ directory or anything under it, whether that's
    # because -GeneratedWrapperDir was left at its production default or
    # was itself (accidentally or maliciously) pointed there. Comparison is
    # done on fully-resolved paths so a relative/trailing-slash/case
    # variation of the same real directory cannot slip through. Production
    # behavior when the sentinel is absent is completely unchanged: no
    # caller is required to pass -GeneratedWrapperDir.
    if (-not [string]::IsNullOrEmpty($env:ADM_PESTER_TEST_ACTIVE)) {
        $admProductionGeneratedDir = [IO.Path]::GetFullPath((Join-Path $RepositoryPath "manager\generated")).TrimEnd('\')
        if ([string]::IsNullOrWhiteSpace($GeneratedWrapperDir)) {
            throw "GENERATED_WRAPPER_DIR_REQUIRED_UNDER_TEST: `$env:ADM_PESTER_TEST_ACTIVE is set; New-AdmHiddenScheduledTaskAction requires an explicit -GeneratedWrapperDir so the generated .vbs wrapper (for WrapperName '$WrapperName') is never written into the real repository tree ('$admProductionGeneratedDir')."
        }
        $admResolvedWrapperDir = [IO.Path]::GetFullPath($GeneratedWrapperDir).TrimEnd('\')
        if ($admResolvedWrapperDir -eq $admProductionGeneratedDir -or $admResolvedWrapperDir.StartsWith($admProductionGeneratedDir + '\', [StringComparison]::OrdinalIgnoreCase)) {
            throw "GENERATED_WRAPPER_DIR_FORBIDDEN_UNDER_TEST: -GeneratedWrapperDir ('$admResolvedWrapperDir') resolves to or under the real repository's generated-wrapper directory ('$admProductionGeneratedDir') while `$env:ADM_PESTER_TEST_ACTIVE is set; refusing to write a test-generated wrapper (for WrapperName '$WrapperName') there."
        }
    }

    $escapedArgs = $PowerShellArguments.Replace('"', '""')
    $vbsDir = if ($GeneratedWrapperDir) { $GeneratedWrapperDir } else { Join-Path $RepositoryPath "manager\generated" }
    New-Item -ItemType Directory -Force -Path $vbsDir | Out-Null
    $vbsPath = Join-Path $vbsDir "$WrapperName.vbs"

    $vbsLines = @(
        "' Auto-generated by AdmHiddenLaunch.ps1 -- regenerated on every install, do not edit by hand.",
        "' Runs PowerShell with a truly hidden window (WshShell.Run windowStyle=0) so Task",
        "' Scheduler never flashes a console, and propagates the real exit code so",
        "' LastTaskResult stays meaningful.",
        "Set shell = CreateObject(""WScript.Shell"")",
        "exitCode = shell.Run(""powershell.exe $escapedArgs"", 0, True)",
        "WScript.Quit exitCode"
    )
    Set-Content -LiteralPath $vbsPath -Value $vbsLines -Encoding ASCII

    return New-ScheduledTaskAction -Execute "wscript.exe" -Argument "`"$vbsPath`""
}
